<!-- Created by Ariful Islam at 03/22/2020 - 2:54 PM -->
@extends('layouts.master')
@section('content')
    <p><br></p><div class="home-title" style="margin: 60px 0px; padding: 0px; font-family: sans-serif; color: rgb(33, 37, 41); background-color: rgb(246, 247, 249);"><h3 style="margin: 0px 0px 15px; padding: 0px; font-size: 1.575rem; font-weight: 700; line-height: 1.2; color: inherit; text-align: center;">কোভিড-১৯ আক্রান্ত ব্যক্তিদের সংস্পর্শে আসা সন্দেহে থাকা ব্যক্তিদের কোয়ারেন্টিন সম্পর্কে জ্ঞাতব্য</h3><p align="justify" style="margin-bottom: 1rem; padding: 20px 0px 0px; font-size: 17px !important;">কোয়ারান্টাইন এর মাধ্যমে সেই সকল সুস্থ ব্যক্তিদের,
            যারা কোন সংক্রামক রোগে আক্রান্ত ব্যক্তির সংস্পর্শে এসেছেন,
            তাদের অন্য সুস্থ ব্যক্তিদের থেকে আলাদা রাখা হয়,
            গতিবিধি নিয়ন্ত্রণ করা হয় এবং তারা একটি নির্দিষ্ট সময়ের মধ্যে ঐ সংক্রামক রোগে আক্রান্ত হন কিনা তা পর্যবেক্ষণ করা হয়। আন্তর্জাতিক স্বাস্থ্য বিধি (আইএইচআর -২০০৫) এর আর্টিকেল ৩২ অনুসারে,
            যে সব দেশে কোভিড-১৯ এর স্থানীয় সংক্রমণ ঘটেছে সে সব দেশ থেকে যে সব যাত্রী এসেছেন এবং আসবেন (দেশী-বিদেশী যে কোনো নাগরিক),
            যারা দেশে সনাক্তকৃত ৩ জন কোভিড-১৯ আক্রান্ত ব্যক্তিদের সংস্পর্শে এসেছেন,
            এবং যার অথবা যাদের কোন শারীরিক উপসর্গ নেই,
            তাদের ১৪ দিন কোয়ারেন্টিন পালন করা আবশ্যক। ঐ সকল ব্যক্তিদের মধ্যে যাদের বাড়ীতে কোয়ারেন্টিনের নির্দেশাবলী অনুযায়ী পর্যাপ্ত ব্যবস্থা করা সম্ভব,
            যারা নিজেরা (ও তাদের পরিবার) স্বেচ্ছা/ গৃহ কোয়ারেন্টিনের সকল নিয়ম মানার জন্য প্রস্তুত এবং যাদের ক্ষেত্রে পারিবারিক ও সামাজিকভাবে কোয়ারেন্টিন থাকাকালীন প্রয়োজনীয় সকল সামগ্রী নিশ্চিত করা সম্ভব,
            তারা স্বেচ্ছা/ গৃহ কোয়ারেন্টিনে থাকতে পারেন।</p></div><div class="recommendations" style="margin: 0px; padding: 0px; font-family: sans-serif; color: rgb(33, 37, 41); background-color: rgb(246, 247, 249);"><h4 style="margin: 0px 0px 15px; padding: 0px; font-size: 25px; font-weight: 700; line-height: 1.2; color: rgb(1, 112, 192);">স্বেচ্ছা/ গৃহ কোয়ারেন্টিনের জন্য নির্দেশনাবলীঃ</h4><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">অত্যাবশ্যকীয়ভাবে নিজ বাড়ীতে থাকুন</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">হাসপাতালে চিকিৎসা সেবা নেয়া ব্যতীত বাড়ীর বাইরে যাবেন না।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">বাড়ীর বাইরে কাজে,
                স্কুল,
                কলেজ অথবা জনসমাগমে যাওয়া থেকে বিরত থাকুন।</li></ul><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">বাড়ীর অন্যান্য সদস্যদের থেকে আলাদা থাকুন</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">আলো বাতাসের সুব্যবস্থা সম্পন্ন আলাদা ঘরে থাকুন এবং অন্যান্য সদস্যদের থেকে আলাদাভাবে থাকুন। তা সম্ভব না হলে,
                অন্যদের থেকে অন্তত ১ মিটার (৩ ফুট) দুরে থাকুন (ঘুমানোর জন্য পৃথক বিছানা ব্যবহার করুন)।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">যদি সম্ভব হয় তাহলে আলাদা গোসলখানা এবং টয়লেট ব্যবহার করুন। সম্ভব না হলে,
                অন্যদের সাথে ব্যবহার করতে হয় এমন স্থানের সংখ্যা কমান ও ঐ স্থানগুলোতে জানালা খুলে রেখে পর্যাপ্ত আলো-বাতাসের ব্যবস্থা করুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">বুকের দুধ খাওয়ান এমন মা শিশুকে বুকের দুধ খাওয়াবেন। শিশুর কাছে যাওয়ার সময় মাস্ক ব্যবহার করুন বং ভালভাবে হাত ধুয়ে নিন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">আপনার সাথে কোন পশু/পাখি রাখবেন না।</li></ul><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">মাস্ক ব্যবহার করুন</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">বাড়ীর অন্যান্য সদস্যদের সাথে একই ঘরে অবস্থান করলে,
                বিশেষ করে ১ মিটারের মধ্যে আসার সময়।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">অত্যাবশ্যকীয় প্রয়োজনে বাড়ী থেকে বের হলে মাস্ক ব্যবহার করুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">মাস্ক পরে থাকাকালীন এটি হাত দিয়ে ধরা থেকে বিরত থাকুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">মাস্ক ব্যবহারের সময় প্রদাহের (সর্দি, থুতু, কাশি, বমি ইত্যাদি) সংস্পর্শে আসলে সঙ্গে সঙ্গে মাস্ক খুলে ফেলুন এবং নতুন মাস্ক ব্যবহার করুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">মাস্ক ব্যবহারের পর ঢাকনাযুক্ত ময়লার পাত্রে ফেলুন এবং সাবান পানি দিয়ে ভাল ভাবে হাত ধুয়ে নিন।</li></ul><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">হাত ধোয়া</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">সাবান ও পানি দিয়ে অন্তত ২০ সেকেন্ড ধরে হাত ধোবেন (বিশেষ করে যদি হাত দেখতে নোংরা লাগে সাবান-পানি ব্যবহার করুন)। প্রয়োজনে হ্যান্ড স্যানিটাইজার ব্যবহার করা যেতে পারে।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">অপরিষ্কার হাতে চোখ,
                নাক ও মুখ স্পর্শ করবেন না।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">সাবান-পানি ব্যবহারের পর টিস্যু দিয়ে হাত শুকনো করে ফেলুন। টিস্যু না থাকলে শুধুহাত মোছার জন্য নির্দিষ্ট তোয়ালে/ গামছা ব্যবহার করুন এবং ভিজে গেলে বদলে ফেলুন।</li></ul><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">মুখ ঢেকে হাঁচি কাশি দিন</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">কাশি শিষ্টাচার মেনে চলুন। হাঁচি কাশির সময় টিস্যু পেপার/ মেডিকেল মাস্ক/ কাপড়ের মাস্ক/ বাহুর ভাঁজে মুখ ও নাক ঢেকে রাখুন এবং উপরের নিয়মানুযায়ী হাত পরিষ্কার করুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">টিস্যু পেপার ও মেডিকেল মাস্ক ব্যবহারের পর ঢাকনাযুক্ত বিনে ফেলুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">ব্যক্তিগত ব্যবহার্য সামগ্রী অন্য কারো সাথে ভাগাভাগি করে ব্যবহার করবেন না।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">আপনার খাওয়ার বাসনপত্র- থালা,
                গ্লাস,
                কাপ ইত্যাদি,
                তোয়ালে,
                বিছানার চাদর অন্য কারো সাথে ভাগাভাগি করে ব্যবহার করবেন না ।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">এ সকল জিনিসপত্র ব্যবহারের পর সাবান-পানি দিয়ে ভালোভাবে পরিষ্কার করে ফেলুন।</li></ul><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">কখন আপনার কোয়ারেন্টিন শেষ হবে?</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">চিকিৎসকের পরামর্শ অনুযায়ী আপনার কোয়ারেন্টিন শেষ হবে। চিকিৎসকের সিদ্ধান্তমতে একজন হতে অন্যজনের কোয়ারেন্টিন-এর সময়সীমা আলাদা হতে পারে। তবে,
                এ পর্যন্তপাওয়া তথ্য-উপাত্তের ভিত্তিতে এ সময়সীমা ১৪ দিন।</li></ul><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">আপনি কোয়ারেন্টিনে থাকাকালীন যা করতে পারেন-</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">COVID-19 সম্পর্কে জানতে পারেন। WHO,
                CDC,
                IEDCR এর ওয়েবসাইটে এ সংক্রান্ত হালনাগাদ তথ্য পেতে পারেন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">পরিবার ও বন্ধু-বান্ধবের সাথে ফোন/ মোবাইল/ ইন্টারনেটের সাহায্যে যোগাযোগ রাখুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">শিশুকে তার জন্য প্রযোজ্যভাবে বোঝান। তাদেরকে পর্যাপ্ত খেলার সামগ্রী দিন এবং খেলনাগুলো খেলার পরে জীবাণুমুক্ত করুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">আপনার দৈনন্দিন রুটিন,
                যেমন- খাওয়া,
                হালকা ব্যায়াম ইত্যাদি মেনে চলুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">সম্ভব হলে বাসা থেকে অফিসের কাজ করতে থাকুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">বইপড়া,
                গান শোনা,
                সিনেমা দেখা অথবা উপর্যুক্ত নিয়মগুলোর সাথে পরিপন্থী নয় এমন যে কোন বিনোদনমূলক কাজে নিজেকে সম্পৃক্ত করুন বা ব্যস্ত রাখুন।</li></ul><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">পরিবারের সদস্যদের জন্য নির্দেশাবলী</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">কোয়ারেন্টিনে আছেন এমন ব্যক্তির সাথে কোন অতিথিকে দেখা করতে দিবেন না।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">যিনি কোয়ারেন্টিনে আছেন,
                তার ঘরে থাকা নিশ্চিত করুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">বর্তমানে সুস্থ আছেন এবং যার দীর্ঘমেয়াদী রোগসমূহ (যেমনঃ ডায়াবেটিস, উচ্চ রক্তচাপ, ক্যান্সার, অ্যাজমা প্রভৃতি) নেই,
                এমন একজন নির্দিষ্ট ব্যক্তিকে পরিচর্যাকারী হিসেবে নিয়োজিত হতে পারেন। তিনি ঐ ঘরে বা পাশের ঘরে থাকবেন,
                অবস্থান বদল করবেন না।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">পরিচর্যাকারী নিন্মলিখিত যে কোন কাজ করার পর প্রতিবার উপরের নিয়মে দুই হাত পরিষ্কার করবেনঃ</li></ul><ul class="padding-left" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 60px; list-style-type: circle;"><li style="margin: 0px; padding: 0px; font-size: 14px;">কোয়ারেন্টিনে থাকা ব্যক্তির সংস্পর্শে এলে বা তার ঘরে ঢুকলে</li><li style="margin: 0px; padding: 0px; font-size: 14px;">খাবার তৈরীর আগে ও পরে</li><li style="margin: 0px; padding: 0px; font-size: 14px;">খাবার আগে</li><li style="margin: 0px; padding: 0px; font-size: 14px;">টয়লেট ব্যবহারের পরে</li><li style="margin: 0px; padding: 0px; font-size: 14px;">গ্লাভস পরার আগে ও খোলার পরে</li><li style="margin: 0px; padding: 0px; font-size: 14px;">যখনই হাত দেখে নোংরা মনে হয়</li></ul><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">খালি হাতে ঐ ঘরের কোন কিছু স্পর্শ করবেন না।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">কোয়ারেন্টিনে থাকা ব্যক্তির ব্যবহৃত বা তার পরিচর্যায় ব্যবহৃত মাস্ক,
                গ্লাভস,
                টিস্যু ইত্যাদি অথবা অন্য আবর্জনা ঐ রুমে রাখা ঢাকনাযুক্ত ময়লার পাত্রে রাখুন। এ সকল আবর্জনা উন্মুক্ত স্থানে না ফেলে পুড়িয়ে ফেলুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">ঘরের মেঝে,
                আসবাবপত্রের সকল পৃষ্ঠতল,
                টয়লেট ও বাথরুম প্রতিদিন অন্তত একবার পরিষ্কার করুন। পরিষ্কারের জন্য ১ লিটার পানির মধ্যে ২০ গ্রাম (২ টেবিল চামচ পরিমাণ) ব্লিচিং পাউডার মিশিয়ে দ্রবণ তৈরী করুন ও ঐ দ্রবণ দিয়ে উক্ত সকল স্থান ভালোভাবে মুছে ফেলুন। তৈরীকৃত দ্রবণ সর্বোচ্চ ২৪ ঘন্টা পর্যন্ত ব্যবহার করা যাবে।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">কোয়ারেন্টিনে থাকা ব্যক্তিকে নিজের কাপড়,
                বিছানার চাদর,
                তোয়ালে ইত্যাদি ব্যবহৃত কাপড় গুঁড়া সাবান/ কাপড় কাচা সাবান ও পানি দিয়ে ভালোভাবে পরিষ্কার করতে বলুন এবং পওে ভালোভাবে শুকিয়ে ফেলুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">নোংরা কাপড় একটি লন্ড্রি ব্যাগে আলাদা রাখুন। মল-মূত্র বা নোংরা লাগা কাপড় ঝাঁকাবেন না এবং নিজের শরীর বা কাপড়ে যেন না লাগে তা খেয়াল করুন।</li></ul><h5 style="margin: 0px 0px 15px; padding: 30px 0px 0px; font-size: 18px; font-weight: 700; line-height: 1.2; color: rgb(12, 187, 134);">কোয়ারান্টাইনে থাকা ব্যক্তির জন্য বিশেষ নির্দেশনা</h5><ul class="wtd" style="margin-right: 0px; margin-bottom: 1rem; margin-left: 0px; padding: 0px 0px 0px 30px; font-size: 18px;"><li style="margin: 0px; padding: 0px; font-size: 14px;">স্থানীয় সরকারী হাসপাতাল এবং আইইডিসিআর-এ যোগাযোগের প্রয়োজনীয় ফোন নম্বরগুলো সংগ্রহে রাখুন।</li><li style="margin: 0px; padding: 0px; font-size: 14px;">যদি কোয়ারেন্টিনে থাকাকালীন কোন উপসর্গ দেখা দেয় (১০০ ডিগ্রি ফারেনহাইট/৩৮০ ডিগ্রি সেলসিয়াস এর বেশি কাশি/ সর্দি/ গলাব্যথা/ শ্বাসকষ্ট ইত্যাদি),
                তবে অতি দ্রত আইইডিসিআর-এর হটলাইন নম্বরে অবশ্যই যোগাযোগ করুন এবং পরবর্তী করণীয় জেনে নিন-</li><p style="margin-bottom: 1rem; padding: 0px; font-size: 14px;"><a href="callto:01401184551" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01401184551</a>&nbsp;
                <a href="callto:01401184554" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01401184554</a>&nbsp;
                <a href="callto:01550064901" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01550064901</a>&nbsp;
                <a href="callto:01550064902" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01550064902</a>&nbsp;
                <a href="callto:01550064903" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01550064903</a>&nbsp;
                <a href="callto:01550064904" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01550064904</a>&nbsp;
                <a href="callto:01550064905" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01550064905</a>&nbsp;
                <a href="callto:01401184555" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01401184555</a>&nbsp;
                <a href="callto:01401184556" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01401184556</a>&nbsp;
                <a href="callto:01401184559" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01401184559</a>&nbsp;
                <a href="callto:01401184560" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01401184560</a>&nbsp;
                <a href="callto:01401184563" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01401184563</a>&nbsp;
                <a href="callto:01401184568" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01401184568</a>&nbsp;
                <a href="callto:01937110011" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01937110011</a>&nbsp;
                <a href="callto:01937000011" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01937000011</a>&nbsp;
                <a href="callto:01927711784" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01927711784</a>&nbsp;
                <a href="callto:01927711785" style="margin: 0px; padding: 0px; color: rgb(52, 144, 220); outline: none !important;">01927711785</a>&nbsp;
                ।</p></ul></div>

    <iframe src="https://dghs.gov.bd/images/docs/Notice/2020/Stress-for-children-during-covid-19--bangla.pdf" height="2000px" width="100%" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen>

    <iframe src="https://dghs.gov.bd/images/docs/Notice/2020/Stress-during-covid-19--bangla.pdf" height="2000px" width="100%" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen>

    @endsection
