<?php
/**
 * Created by Pigeon Soft.
 * User: Ariful Islam
 * Date: 15-Aug-18
 * Time: 4:19 PM
 */
if (!function_exists('en2bn')) {
    function en2bn($number)
    {
        $bn = array("১", "২", "৩", "৪", "৫", "৬", "৭", "৮", "৯", "০");
        $en = array("1", "2", "3", "4", "5", "6", "7", "8", "9", "0");
        return str_replace($en, $bn, $number);
    }

}
if (!function_exists('txten2bn')) {
    function txten2bn($text)
    {
        $bn = array(
            "আফগানিস্তান",
            "আলবেনিয়া",
            "আলজেরিয়া",
            "এ্যান্ডোরা",
            "অ্যাঙ্গোলা",
            "অ্যান্টিগুয়া ও বার্বুডা",
            "আর্জেন্টিনা",
            "আর্মেনিয়া",
            "অস্ট্রেলিয়া",
            "অস্ট্রিয়া",
            "আজারবাইজান",
            "বাহামা",
            "বাহরাইন",
            "বাংলাদেশ",
            "বার্বাডোস",
            "বেলারুশ",
            "বেলজিয়াম",
            "বেনিন",
            "ভুটান",
            "বলিভিয়া",
            "বসনিয়া ও হার্জেগোভিনা",
            "ব্রাজিল",
            "ব্রুনেই",
            "বুলগেরিয়া",
            "বুর্কিনা ফাসো",
            "কাবো ভার্দে",
            "কম্বোডিয়া",
            "ক্যামেরুন",
            "কানাডা",
            "কেপ ভার্দে",
            "মধ্য আফ্রিকান প্রজাতন্ত্র",
            "চাদ",
            "চিলি",
            "চীন",
            "কলম্বিয়া",
            "কঙ্গো (ব্রাজাভিল)",
            "কঙ্গো (কিনসাসা)",
            "কোস্টারিকা",
            "আইভরি কোস্ট",
            "ক্রোয়েশিয়া",
            "ক্রুস শীপ",
            "কিউবা",
            "সাইপ্রাস",
            "Czechia",
            "ডেনমার্ক",
            "জিবুতি",
            "ডোমিনিকা",
            "ডোমিনিকান প্রজাতন্ত্র",
            "পূর্ব তিমুর",
            "ইকুয়েডর",
            "মিশর",
            "এল সালভাদর",
            "নিরক্ষীয় গিনি",
            "ইরিত্রিয়া",
            "এস্তোনিয়া",
            "Eswatini",
            "ইথিওপিয়া",
            "ফিজি",
            "ফিনল্যান্ড",
            "ফ্রান্স",
            "গ্যাবন",
            "গাম্বিয়া দ্য",
            "জর্জিয়া",
            "জার্মানি",
            "ঘানা",
            "গ্রীস",
            "গ্রানাডা",
            "গুয়াতেমালা",
            "গিনি",
            "গায়ানা",
            "হাইতি",
            "হোলি সী",
            "হন্ডুরাস",
            "হাঙ্গেরি",
            "আইসল্যান্ড",
            "ভারত",
            "ইন্দোনেশিয়া",
            "ইরান",
            "ইরাক",
            "আয়ারল্যান্ড",
            "ইস্রায়েল",
            "ইতালি",
            "জ্যামাইকা",
            "জাপান",
            "জর্ডান",
            "কাজাখস্তান",
            "কেনিয়া",
            "কোরিয়া, দক্ষিণ",
            "কসোভো",
            "কুয়েত",
            "কিরগিজস্তান",
            "লাটভিয়া",
            "লেবানন",
            "লাইবেরিয়া",
            "লিচেনস্টেইন",
            "লিথুয়ানিয়া",
            "লুক্সেমবার্গ",
            "মাদাগাস্কার",
            "মালয়েশিয়া",
            "মালদ্বীপ",
            "মাল্টা",
            "মার্টিনিক",
            "মরিতানিয়া",
            "মরিশাস",
            "মেক্সিকো",
            "মোল্দাভিয়া",
            "মোনাকো",
            "মঙ্গোলিয়া",
            "মন্টিনিগ্রো",
            "মরক্কো",
            "মোজাম্বিক",
            "নামিবিয়া",
            "নেপাল",
            "নেদারল্যান্ডস",
            "নিউজিল্যান্ড",
            "নিকারাগুয়া",
            "নাইজার",
            "নাইজেরিয়া",
            "উত্তর ম্যাসেডোনিয়া",
            "নরওয়ে",
            "ওমান",
            "পাকিস্তান",
            "পানামা",
            "পাপুয়া নিউ গিনি",
            "প্যারাগুয়ে",
            "পেরু",
            "ফিলিপাইন",
            "পোল্যান্ড",
            "পর্তুগাল",
            "কাতার",
            "রোমানিয়া",
            "রাশিয়া",
            "রুয়ান্ডা",
            "সেন্ট লুসিয়া",
            "সেন্ট ভিনসেন্ট ও গ্রেনাডাইন দ্বীপপুঞ্জ",
            "সান মারিনো",
            "সৌদি আরব",
            "সেনেগাল",
            "সার্বিয়া",
            "সিসিলি",
            "সিঙ্গাপুর",
            "স্লোভাকিয়া",
            "স্লোভানিয়া",
            "সোমালিয়া",
            "দক্ষিন আফ্রিকা",
            "স্পেন",
            "শ্রীলংকা",
            "সুদান",
            "সুরিনাম",
            "সুইডেন",
            "সুইজারল্যান্ড",
            "সিরিয়া",
            "তাইওয়ান *",
            "তাঞ্জানিয়া",
            "থাইল্যান্ড",
            "পূর্ব তিমুর",
            "তোগো",
            "ত্রিনিদাদ ও টোবাগো",
            "তিউনিশিয়া",
            "তুরস্ক",
            "উগান্ডা",
            "ইউক্রেনে",
            "সংযুক্ত আরব আমিরাত",
            "যুক্তরাজ্য",
            "উরুগুয়ে",
            "ইউএস",
            "উজবেকিস্তান",
            "ভেনিজুয়েলা",
            "ভিয়েতনাম",
            "জাম্বিয়া",
            "জিম্বাবুয়ে"
        );
        $en = array(
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas The",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Congo (Brazzaville)",
            "Congo (Kinshasa)",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cruise Ship",
            "Cuba",
            "Cyprus",
            "Czechia",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia The",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guyana",
            "Haiti",
            "Holy See",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Korea, South",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Latvia",
            "Lebanon",
            "Liberia",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malaysia",
            "Maldives",
            "Malta",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "San Marino",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Somalia",
            "South Africa",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan*",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "Uruguay",
            "US",
            "Uzbekistan",
            "Venezuela",
            "Vietnam",
            "Zambia",
            "Zimbabwe"
        );
        return str_replace($en, $bn, $text);
    }

}
